[black.tool]
line-length = 88
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/bin    # exclude bin directory
)
'''
[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[tool.ruff.lint]
ignore = [

]
extend-select = [
   'RUF100', # Require valid "noqa" comments
   'UP', # pyupgrade rules
   'D',  # pydocstyle rules
   # Hatch Default Selected Rules (to match P2 config) excluding
   # "preview" rules and rules already mentioned above (UP).
   # Copied from
   # https://hatch.pypa.io/latest/config/internal/static-analysis/#selected-rules
   'A001',
   'A002',
   'A003',
   'ARG001',
   'ARG002',
   'ARG003',
   'ARG004',
   'ARG005',
   'ASYNC100',
    # Replacement for ASYNC101/102
   'ASYNC220',
    # Replacement for ASYNC101/102
   'ASYNC221',
    # Replacement for ASYNC101/102
   'ASYNC222',
    # Replacement for ASYNC101/102
   'ASYNC230',
    # Replacement for ASYNC101/102
   'ASYNC251',
   'B002',
   'B003',
   'B004',
   'B005',
   'B006',
   'B007',
   'B008',
   'B009',
   'B010',
   'B011',
   'B012',
   'B013',
   'B014',
   'B015',
   'B016',
   'B017',
   'B018',
   'B019',
   'B020',
   'B021',
   'B022',
   'B023',
   'B024',
   'B025',
   'B026',
   'B028',
   'B029',
   'B030',
   'B031',
   'B032',
   'B033',
   'B034',
   'B035',
   'B904',
   'B905',
   'BLE001',
   'C400',
   'C401',
   'C402',
   'C403',
   'C404',
   'C405',
   'C406',
   'C408',
   'C409',
   'C410',
   'C411',
   'C413',
   'C414',
   'C415',
   'C416',
   'C417',
   'C418',
   'C419',
   'COM818',
   'DTZ001',
   'DTZ002',
   'DTZ003',
   'DTZ004',
   'DTZ005',
   'DTZ006',
   'DTZ007',
   'DTZ011',
   'DTZ012',
   'E101',
   'E401',
   'E402',
   'E701',
   'E702',
   'E703',
   'E711',
   'E712',
   'E713',
   'E714',
   'E721',
   'E722',
   'E731',
   'E741',
   'E742',
   'E743',
   'E902',
   'EM101',
   'EM103',
   'EXE001',
   'EXE002',
   'EXE003',
   'EXE004',
   'EXE005',
   'F401',
   'F402',
   'F403',
   'F404',
   'F405',
   'F406',
   'F407',
   'F501',
   'F502',
   'F503',
   'F504',
   'F505',
   'F506',
   'F507',
   'F508',
   'F509',
   'F521',
   'F522',
   'F523',
   'F524',
   'F525',
   'F541',
   'F601',
   'F602',
   'F621',
   'F622',
   'F631',
   'F632',
   'F633',
   'F634',
   'F701',
   'F702',
   'F704',
   'F706',
   'F707',
   'F722',
   'F811',
   'F821',
   'F822',
   'F823',
   'F841',
   'F842',
   'F901',
   'FA100',
   'FA102',
   'FBT001',
   'FBT002',
   'FLY002',
   'G001',
   'G002',
   'G003',
   'G010',
   'G101',
   'G201',
   'G202',
   'I001',
   'I002',
   'ICN001',
   'ICN002',
   'ICN003',
   'INT001',
   'INT002',
   'INT003',
   'ISC003',
   'LOG001',
   'LOG002',
   'LOG007',
   'LOG009',
   'N801',
   'N802',
   'N803',
   'N804',
   'N805',
   'N806',
   'N807',
   'N811',
   'N812',
   'N813',
   'N814',
   'N815',
   'N816',
   'N817',
   'N818',
   'N999',
   'PERF101',
   'PERF102',
   'PERF401',
   'PERF402',
   'PGH005',
   'PIE790',
   'PIE794',
   'PIE796',
   'PIE800',
   'PIE804',
   'PIE807',
   'PIE808',
   'PIE810',
   'PLC0105',
   'PLC0131',
   'PLC0132',
   'PLC0205',
   'PLC0208',
   'PLC0414',
   'PLC3002',
   'PLE0100',
   'PLE0101',
   'PLE0116',
   'PLE0117',
   'PLE0118',
   'PLE0237',
   'PLE0241',
   'PLE0302',
   'PLE0307',
   'PLE0604',
   'PLE0605',
   'PLE1142',
   'PLE1205',
   'PLE1206',
   'PLE1300',
   'PLE1307',
   'PLE1310',
   'PLE1507',
   'PLE1700',
   'PLE2502',
   'PLE2510',
   'PLE2512',
   'PLE2513',
   'PLE2514',
   'PLE2515',
   'PLR0124',
   'PLR0133',
   'PLR0206',
   'PLR0402',
   'SIM101',
   'PLR1711',
   'PLR1714',
   'PLR1722',
   'PLR2004',
   'PLR5501',
   'PLW0120',
   'PLW0127',
   'PLW0129',
   'PLW0131',
   'PLW0406',
   'PLW0602',
   'PLW0603',
   'PLW0711',
   'PLW1508',
   'PLW1509',
   'PLW1510',
   'PLW2901',
   'PLW3301',
   'PT001',
   'PT002',
   'PT003',
   'PT006',
   'PT007',
   'PT008',
   'PT009',
   'PT010',
   'PT011',
   'PT012',
   'PT013',
   'PT014',
   'PT015',
   'PT016',
   'PT017',
   'PT018',
   'PT019',
   'PT020',
   'PT021',
   'PT022',
   'PT023',
   'PT024',
   'PT025',
   'PT026',
   'PT027',
   'PYI001',
   'PYI002',
   'PYI003',
   'PYI004',
   'PYI005',
   'PYI006',
   'PYI007',
   'PYI008',
   'PYI009',
   'PYI010',
   'PYI011',
   'PYI012',
   'PYI013',
   'PYI014',
   'PYI015',
   'PYI016',
   'PYI017',
   'PYI018',
   'PYI019',
   'PYI020',
   'PYI021',
   'PYI024',
   'PYI025',
   'PYI026',
   'PYI029',
   'PYI030',
   'PYI032',
   'PYI033',
   'PYI034',
   'PYI035',
   'PYI036',
   'PYI041',
   'PYI042',
   'PYI043',
   'PYI044',
   'PYI045',
   'PYI046',
   'PYI047',
   'PYI048',
   'PYI049',
   'PYI050',
   'PYI051',
   'PYI052',
   'PYI053',
   'PYI054',
   'PYI055',
   'PYI056',
   'PYI058',
   'RET503',
   'RET504',
   'RET505',
   'RET506',
   'RET507',
   'RET508',
   'RSE102',
   'RUF001',
   'RUF002',
   'RUF003',
   'RUF005',
   'RUF006',
   'RUF007',
   'RUF008',
   'RUF009',
   'RUF010',
   'RUF012',
   'RUF013',
   'RUF015',
   'RUF016',
   'RUF017',
   'RUF018',
   'RUF019',
   'RUF020',
   'RUF100',
   'S101',
   'S102',
   'S103',
   'S104',
   'S105',
   'S106',
   'S107',
   'S108',
   'S110',
   'S112',
   'S113',
   'S201',
   'S202',
   'S301',
   'S302',
   'S303',
   'S304',
   'S305',
   'S306',
   'S307',
   'S308',
   'S310',
   'S311',
   'S312',
   'S313',
   'S314',
   'S315',
   'S316',
   'S317',
   'S318',
   'S319',
   'S321',
   'S323',
   'S324',
   'S501',
   'S502',
   'S503',
   'S504',
   'S505',
   'S506',
   'S507',
   'S508',
   'S509',
   'S601',
   'S602',
   'S604',
   'S605',
   'S606',
   'S607',
   'S608',
   'S609',
   'S611',
   'S612',
   'S701',
   'S702',
   'SIM101',
   'SIM102',
   'SIM103',
   'SIM105',
   'SIM107',
   'SIM108',
   'SIM109',
   'SIM110',
   'SIM112',
   'SIM113',
   'SIM114',
   'SIM115',
   'SIM116',
   'SIM117',
   'SIM118',
   'SIM201',
   'SIM202',
   'SIM208',
   'SIM210',
   'SIM211',
   'SIM212',
   'SIM220',
   'SIM221',
   'SIM222',
   'SIM223',
   'SIM300',
   'SIM910',
   'SIM911',
   'SLF001',
   'SLOT000',
   'SLOT001',
   'SLOT002',
   'T100',
   'T201',
   'T203',
   'TC001',
   'TC002',
   'TC003',
   'TC004',
   'TC005',
   'TC010',
   'TD004',
   'TD005',
   'TD006',
   'TD007',
   'TID251',
   'TID252',
   'TID253',
   'ASYNC100',
   'ASYNC105',
   'ASYNC109',
   'ASYNC110',
   'ASYNC115',
   'TRY003',
   'TRY004',
   'TRY201',
   'TRY301',
   'TRY203',
   'TRY400',
   'TRY401',
   'W291',
   'W292',
   'W293',
   'W505',
   'W605',
   'YTT101',
   'YTT102',
   'YTT103',
   'YTT201',
   'YTT202',
   'YTT203',
   'YTT204',
   'YTT301',
   'YTT302',
   'YTT303',
]
extend-ignore = [
   'D415', # No docstring period
   'D400', # No docstring period
   'D205', # No single summary line
   'D107', # No __init__docstrings
   'D203', # No blank lines before docstring
   'D204', # No blank lines after docstring
   'D413', # No blank lines after last section
   'D406', # Allow : at end of section
   'D212', # Don't care blank lines b4 docstring
   'D213', # Don't care blank lines b4 docstring
   'D407', # No section underline
   'D408', # No section underline
   'G004', # Allow f-strings in logging
   'PYI041', # Allow float | int type hints (the checker does not
             # distinguish, but for correctness, a developer should
             # consider both possibilities.)
   'INP001', # Don't require an __init__.py
   'TRY300', # Allow return in try block
   'TRY002', # Allow messages in exceptions (don't force subclassing)
   'TRY003', # Allow messages in exceptions (don't force subclassing)
   'EM101', # Allow string literal exception messages
   'EM102', # Allow f-string exception messages (it's not a problem to see it
            # in the traceback)
]

[tool.ruff.lint.per-file-ignores]
"**/test_*.py" = [
   "PLR2004", # Allow magic values in tests
   "S101",    # Allow asserts in tests
   "D",       # Don't check docstrings in tests
   "TID252",  # Allow relative imports in tests
   "SLF001",  # Allow private member access in tests
   "E402",    # Allow module level import after top of file
   "S105",    # Allow hardcoded fake secrets
]