python_sources(
    name="lib",
    dependencies=[
# We'll restore pyside6 later
# It was removed because of problems with pyoxidizer
#        "//:3rdparty#pyside6",
        "//wes_tube/impl:lib",
    ],
)